### ISSUE TITLE
Enhance Route Organization Using Laravel Folio Conventions

### ISSUE THREAD

**Issue by jordanpartridge** [jordanpartridge/jordanpartridge.us#126]
## Current Situation
The site currently uses Laravel Folio for route-by-blade file structure, but we can better leverage its capabilities for more maintainable and cleaner routing.

### 1. Reorganize Pages Directory Structure
```
resources/views/pages/
├── index.blade.php
├── _middleware.php       # Global middleware for all pages
├── bike/
│   ├── index.blade.php  # /bike
│   ├── _middleware.php  # Middleware specific to bike routes
│   └── [ride].blade.php # Dynamic route for individual rides
├── blog/
│   ├── index.blade.php  # /blog
│   ├── _middleware.php  # Blog-specific middleware
│   └── [slug].blade.php # Dynamic route for blog posts
├── learn/
│   ├── index.blade.php
│   └── [topic].blade.php
├── profile/
│   └── index.blade.php
└── software-development/
    ├── index.blade.php
    └── [project].blade.php
```

### 2. Implement Route Middleware
Create dedicated middleware files for specific sections:

```php
// resources/views/pages/_middleware.php
<?php

use Illuminate\Http\Request;

return function (Request $request, Closure $next) {
    // Global middleware logic here
    return $next($request);
};
```

### 3. Add Route Parameters Handling
Update dynamic route files to properly handle parameters:

```php
// resources/views/pages/blog/[slug].blade.php
<?php

use function Livewire\Volt\{state};

state(['post' => fn () => Post::whereSlug($slug)->firstOrFail()]);
?>

<x-app-layout>
    <div>
        <!-- Blog post content -->
    </div>
</x-app-layout>
```

### 4. Documentation Updates
- Add route documentation in each major section
- Update README.md with routing conventions
- Add PHPDoc blocks for middleware

## Benefits
1. **Improved Organization**: Clear, hierarchical structure for routes
2. **Better Maintainability**: Each section has its own middleware and parameter handling
3. **Enhanced Developer Experience**: Easier to understand and modify routes
4. **Cleaner Codebase**: Better separation of concerns

## Implementation Steps
1. Create backup of current routes
2. Implement new directory structure
3. Move existing views to new structure
4. Add middleware files
5. Update route parameters
6. Test all routes
7. Update documentation

## Testing Checklist
- [ ] All existing routes work
- [ ] Middleware properly applies
- [ ] Dynamic routes handle parameters correctly
- [ ] No 404 errors on existing URLs
- [ ] SEO meta tags still work
- [ ] Proper breadcrumb generation

## Notes
- This change should be backward compatible
- Can be implemented incrementally
- Requires minimal changes to existing controllers
- Will improve overall code organization

Let me know if you'd like me to start on any specific part of this implementation.

**Comment by jordanpartridge** [comment]
Closing as duplicate of #125
